mooc/catalog/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from rest_framework.routers import DefaultRouter



router = DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'points', views.ProfileViewSet)
router.register(r'lessons', views.LessonsViewSet)
router.register(r'mycourse', views.MyCourseViewSet)

urlpatterns = [
    path('router/', include(router.urls)),
    path('points/<int:pk>', views.get_exp),
    path('cocourse/<int:pk>', views.complete_course),
    path('', views.index, name='index'),
    path('about/', views.about, name='about-page'),
    path('courses/', views.CourseListView.as_view(), name='courses'),
    path('course/<int:pk>', views.CourseDetailView.as_view(), name='course-detail'),
    path('course/<int:pk>/lessons', views.LessonsListView.as_view(), name='lesson'),
    path('lessons/<int:pk>', views.LessonsDetailView.as_view(), name='lesson-detail'),
    path('course/<int:pk>/addtolist', views.addtolist, name='add-course-to-list'),
    path('course/<int:pk>/deletefromlist', views.deletefromlist, name='delete-course-from-list'),
    path('teachers/', views.PostedbyListView.as_view(), name='teachers'),
    path('teacher/<int:pk>', views.PostedbyDetailView.as_view(), name='teacher-detail'),
    path('teacher/create', views.PostedbyCreate.as_view(), name='teacher-create'),
    path('teacher/<int:pk>/update', views.PostedbyUpdate.as_view(), name='teacher-update'),
    path('teacher/<int:pk>/delete', views.PostedbyDelete.as_view(), name='teacher-delete'),
    path('mycourses/', views.ActiveCoursesByUserListView.as_view(), name='my-active'),
    path('profile/', views.view_profile, name='view-profile'),
    path('profile/edit/', views.edit_profile, name='edit-profile'),
    path('change-password/', views.change_password, name='change-password'),
] 

mooc/mooc/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from register import views as v
from catalog import views

from catalog.views import TestView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('testview/', views.TestView, name='test'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('register/', v.register, name='register'),
    path('api-auth/', include('rest_framework.urls')),
    path('badges/', include('pinax.badges.urls', namespace='pinax_badges')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static (settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mooc/catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User as AuthUser
from django.db.models.signals import post_save
from django.template.defaultfilters import slugify
from pinax.badges.base import Badge, BadgeAwarded
from pinax.badges.registry import badges

# Create your models here.
class Field(models.Model):
    name = models.CharField(max_length=200, help_text='Enter a field (e.g. Physics) ')
    info = models.CharField(max_length=600, help_text='Enter some info about the field')

    def __str__(self):
        return f'{self.name}'        

class User(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    born_date = models.DateField(null=True, blank=True)
    email = models.EmailField(max_length=50)
    username = models.CharField(max_length=50)

    class Meta:
        ordering = ['last_name', 'first_name', 'username', 'email']
    
    def get_absolute_url(self):
        return reverse('user-detail', args=[str(self.id)])
    
    def __str__(self):
        return f'{self.last_name}, {self.first_name}, {self.username}, {self.email}'
    
class Course(models.Model):
    title = models.CharField(max_length=50)
    teacher = models.ForeignKey(User, on_delete=models.CASCADE)
    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the course')
    field = models.ManyToManyField(Field, help_text='Select a field for this course')

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return reverse('course-detail', kwargs={'pk': self.pk})

    def display_field(self):
        return ', '.join(field.name for field in self.field.all()[:3])
    display_field.short_description = 'Field'

class Postedby(models.Model):
    class Meta:
        verbose_name_plural = "Posted by"
    
    op = models.ForeignKey(User, on_delete=models.CASCADE)
    courses = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True, blank=True)
    posted_date = models.DateField(auto_now_add=True)
    last_modified_date = models.DateField(auto_now=True)
    
    def __str__(self):
        return f'{self.op},{self.courses}'
    
    def get_absolute_url(self):
        return reverse('teacher-detail', kwargs={'pk': self.pk})
    
class MyCourse(models.Model):
    active = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    course = models.ForeignKey(Course, on_delete=models.SET_NULL, null=True, blank=True)
    last_accessed = models.DateField(auto_now=True)

    CURRENT_STATUS = (
        ('n', 'Not started'),
        ('i', 'Incomplete'),
        ('c', 'Completed'),
    )

    status = models.CharField(
        max_length=1,
        choices=CURRENT_STATUS,
        blank=True,
        default='n',
        help_text='Courses taken'
    )

    class Meta:
        ordering = ['last_accessed']


    def __str__(self):
        return f'{self.course.title}'


class Lessons(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    title = models.TextField(max_length=150 , help_text='Lesson title')
    text = models.TextField(max_length=10000 , help_text='Helping text or other infomartion that you want on display', default='')
    arxeio = models.FileField(upload_to='media')
    order = models.PositiveSmallIntegerField(blank=False, null=False, default=0)


    CURRENT_STATUS = (
        ('n', 'Not started'),
        ('i', 'Incomplete'),
        ('c', 'Completed'),
    )

    status = models.CharField(
        max_length=1,
        choices=CURRENT_STATUS,
        blank=True,
        default='n',
        help_text='Courses taken'
    )

    class Meta:
        verbose_name_plural = "Lessons"
        ordering = ['order',]

    def __str__(self):
        return f'{self.title}'

    def get_absolute_url(self):
        return reverse('lesson-detail', kwargs={'pk': self.pk})


class PointsBadge(Badge):
    slug = "points"
    levels = [
        "Bronze",
        "Silver",
        "Gold",
    ]
    events = [
        "points_awarded",
    ]
    multiple = False

    def award(self, **state):
        user = state["user"]
        points = user.get_profile().points
        if points > 500:
            return BadgeAwarded(level=3)
        elif points > 50:
            return BadgeAwarded(level=2)
        elif points > 5:
            return BadgeAwarded(level=1)

badges.register(PointsBadge)

class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete = models.CASCADE
    )
    points = models.IntegerField (
        default = 0
    )

    CURRENT_LEVEL = (
        (1, 'Level 1'),
        (2, 'Level 2'),
        (3, 'Level 3'),
        (4, 'Level 4'),
        (5, 'Level 5'),
        (6, 'Level 6'),
        (7, 'Level 7'),
        (8, 'Level 8'),
        (9, 'Level 9'),
        (10, 'Level 10'),
        (11, 'Level 11'),
        (12, 'Level 12'),
        (13, 'Level 13'),
        (14, 'Level 14'),
        (15, 'Level 15'),
    )

    status = models.IntegerField(
        # max_length=2,
        choices=CURRENT_LEVEL,
        blank=False,
        default=1,
        help_text='User Level'
    )

    CURRENT_RANK = (
        (1, 'Bronze'),
        (2, 'Silver'),
        (3, 'Gold'),
        (4, 'Platinum'),
        (5, 'Diamond'),
        (6, 'Master'),
        (7, 'GrandMaster'),
    )

    rank_status = models.IntegerField(
        # max_length=1,
        choices=CURRENT_RANK,
        blank=False,
        default=1,
        help_text='User Rank'
    )

    # def status_verbose(self):
    #     return dict(Profile.CURRENT_LEVEL)[self.status]

    # def rank_verbose(self):
    #     return dict(Profile.CURRENT_RANK)[self.rank_status]


    def award_points (self, points):
        self.points += points
        self.save()


class Badges(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='badg/')

    def __str__(self):
        return f'{self.pk}'

class UserBadge(models.Model):
    user = models.ForeignKey(
        User,
        on_delete = models.CASCADE
    )
    badg = models.ForeignKey(Badges, on_delete=models.CASCADE, null=True, blank=True)

mooc/catalog/forms.py
from django import forms
from django.contrib.auth.models import User as AuthUser
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from catalog.models import User

class EditProfileForm(UserChangeForm):
    password = None

    class Meta:
        model = AuthUser
        fields = [
            'first_name',
            'last_name',
            'email'
            ]

mooc/catalog/templates/catalog/change_password.html
{% extends 'base_generic.html' %}

{% block content %}

<title>Profile</title>
<div class="container">
    <h2 class="text-center">Change Password</h2>
    <p>
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button class="btn btn-outline-dark btn-lg" type="sumbit">Sumbit</button>
        </form>

    </p>


</div>


{% endblock %}

mooc/catalog/templates/catalog/course_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Title: {{course.title}}</h1>

    <p><strong>Teacher:</strong> <a href="{% url 'user-detail' course.teacher.id %}">{{ course.teacher.last_name }} {{ course.teacher.first_name }}</a></p> 
    <p><strong>Summary:</strong> {{ course.summary }}</p>
    <p><strong>Field:</strong> {{ course.field.all|join:", " }}</p>  
    <p><strong>Start your lessons </strong><a href="{% url 'lesson' course.id %}">here</a>!!</p>

    

{% endblock content %}

mooc/catalog/templates/catalog/course_list.html
{% extends 'base_generic.html' %}

{% block content %}

    <div class="gradient">
        <div class="container">
            <h1 class="course-card-heading"> Full Course List</h1>
            <h2 class="text-center">Select from our available courses below.</h2>
            <p class="someinfo">You can add, remove courses from your list at any time.<br> Feel free to create your own curriculum.  </p>
            <div class="row">
                {% if course_list %}
                    {% for course in course_list %}
                        <div class="col-lg-8 offset-lg-2">                                
                            <div class="card-main">
                                <div class="course-card-title">
                                    <h4 class="ccdt">{{course.title}}</h4>
                                    <a href="{% url 'lesson' course.id %}" class="button button--secondary" style="text-decoration: none;">View Course</a></p>
                                    
                                    {% if user.is_authenticated %}
                                        <a href="{% url 'add-course-to-list' course.id %}" class="button button--optional" style="text-decoration: none;">Add to List!</a>
                                    {% endif %}
                                </div>
                                <p class="course-card-summary">{{course.summary}}</p>
                             
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    <p>There are no courses in the site.</p>
               {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

mooc/catalog/templates/catalog/edit_profile.html
{% extends 'base_generic.html' %}
{% load crispy_forms_tags %}


{% block content %}

<title>Profile</title>
<div class="container">
    <h2 class="text-center">Edit profile</h2>
      <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-outline-dark btn-lg" type="sumbit">Sumbit</button>      
      </form>
    <br>
  <a class="btn btn-danger" href="{% url 'change-password' %}">Change my password</a>
</div>


{% endblock %}

mooc/catalog/templates/catalog/lessons_detail.html
{% extends "base_generic.html" %}
{% load static %}

{% block content %}


<div class="gradient">
    <div class="container">
        <div class="row">
            
                <div class="cotitle">
                    <h1 class="ctitle"> {{lessons.title}} </h1>
                    <div class="sum">
                        <h2 class="sum_h">Overview</h2>
                        <p class="sum_p"> {{lessons.text}} </p>
                    </div>
                                      
                    <div class="card-main">

                       

                        <div class="top-bar">
        
                            <button class="btn" id="prev-page">
                                <i class="fas fa-arrow-circle-left"></i> Prev Page
                            </button>
                            <input type="number" value="1" id="current_page">
                            <button class="btn" id="next-page">
                                Next Page <i class="fas fa-arrow-circle-right"></i>
                            </button>
                    
                            <span class="page-info">
                                page <span id="page-num"></span> of <span id="page-count"></span>
                            </span>
                    
                        </div>
                        
                        <canvas id="pdf-render"></canvas>

                    </div>
                </div>
            
        </div>

        <div class="text-center">
            <h3><strong>Additional Resources</strong></h3>
            <h4><p><a href="#">First source</a><br>
            <a href="#">Second source</a></p></h4>
        </div>
        
        <div class="text-center">
            {% if lessons.order > 1 %}
                <a class="button button--secondary" style="text-decoration: none;" href="{% url 'lesson-detail' lessons.pk|add:-1 %}">Previous Lesson</a>
            {% endif %}
            {% if lessons.order < 15 %}
                <a onclick="AddPoints('{{profile.id}}')" class="button button--secondary" style="text-decoration: none;" href="{% url 'lesson-detail' lessons.pk|add:1 %}">Next Lesson</a>
            {% endif %}
            {% if lessons.order == 15 %}
                <a onclick="CompleteCourse('{{profile.id}}','{{lessons.course}}','{{lessons.course.id}}')" class="button button--secondary" style="text-decoration: none;" href="{% url 'view-profile' %}">Complete Course</a>
            {% endif %}  
        </div>

    </div>
</div>
<script src="https://cdn.jsdelivr.net/npm/js-cookie@rc/dist/js.cookie.min.js"></script>
<script
  src="https://code.jquery.com/jquery-3.4.1.min.js"
  integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
  crossorigin="anonymous"></script>
<script type="text/javascript">

    function AddPoints(profile) {
        var csrftoken = Cookies.get('csrftoken');
        var xhttp = new XMLHttpRequest();
        var url = 'http://127.0.0.1:8000/points/';
        
        xhttp.open("PUT", url + profile.toString(), false);
        xhttp.setRequestHeader('Content-type', 'application/json; charset=utf-8');
        xhttp.setRequestHeader("X-CSRFToken", csrftoken);
        var data = JSON.stringify({
            "profile": profile
        });
        xhttp.send(data);
    }
</script>

<script type="text/javascript">

    function CompleteCourse(profile, course, cid) {
        var csrftoken = Cookies.get('csrftoken');
        var xhttp = new XMLHttpRequest();
        var url = 'http://127.0.0.1:8000/cocourse/';

        xhttp.open("PUT", url + profile.toString(), false);
        xhttp.setRequestHeader('Content-type', 'application/json; charset=utf-8');
        xhttp.setRequestHeader("X-CSRFToken", csrftoken);
        var data = JSON.stringify({
            "profile": profile,
            "course": course,
            "cid": cid,
        });
        xhttp.send(data);
    }


</script>


<script src="https://mozilla.github.io/pdf.js/build/pdf.js"></script>
<script>
    const url = '../{{lessons.arxeio}}'

    console.log(url)

    let pdfDoc = null,
        pageNum = 1,
        pageIsRendering = false,
        pageNumIsPending = null;

    const scale = 1.45,
        canvas = document.querySelector('#pdf-render'),
        ctx = canvas.getContext('2d');

    const renderPage = num => {
        pageIsRendering = true;

        pdfDoc.getPage(num).then(page => {
            
            const viewport = page.getViewport({ scale });
            canvas.height = viewport.height;
            canvas.width = viewport.width;

            const renderCtx = {
                canvasContext: ctx,
                viewport
            }

            page.render(renderCtx).promise.then(() => {
                pageIsRendering = false;

                if(pageNumIsPending != null){
                    renderPage(pageNumIsPending);
                    pageNumIsPending = null;  
                }     
            });

            document.querySelector('#page-num').textContent = num;
        });
    };

    const queueRenderPage = num => {
        if(pageIsRendering) {
            pageNumIsPending = num;
        } else {
            renderPage(num);
        }
    }

    const showPrevPage = () => {
        if(pageNum <= 1) {
            return;
        }
        pageNum--;
        queueRenderPage(pageNum);
    }

    const showNextPage = () => {
        if(pageNum >= pdfDoc.numPages) {
            return;
        }
        pageNum++;
        queueRenderPage(pageNum);
    }

    pdfjsLib.getDocument(url).promise.then(pdfDoc_ => {
        pdfDoc = pdfDoc_;
    

        document.querySelector('#page-count').textContent = pdfDoc.numPages;

        renderPage(pageNum)
    });

    document.querySelector('#prev-page').addEventListener('click',showPrevPage);
    document.querySelector('#next-page').addEventListener('click',showNextPage);
</script>




{% endblock %}

mooc/catalog/templates/catalog/lessons_list.html
{% extends "base_generic.html" %}

{% block content %}  
<div class="gradient">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 offset-lg-2">
                <div class="cotitle">
                    <h1 class="ctitle"> {{course}} <h1>
                        
                            <div class="teachfield">
                                <h4><strong>Teacher: </strong> <a class="linkinfo" href="{% url 'teacher-detail' course.teacher.id %}">{{ course.teacher.last_name }} {{ course.teacher.first_name }}</a></h4>
                                <h4><strong>Field: </strong> {{ course.field.all|join:", " }}</h4>  
                            </div>
                        
                    <div class="sum">
                        <div class="card-main">
                            <h2 class="sum_o">Overview</h2>
                            <p class="sum_p"> {{course.summary}} </p>
                        </div>
                    </div>
                    <div class="card-main">

                        {% if lessons_list %}
                            {% for lessons in lessons_list %}
                                <h3 class="mathimata">
                                    <a class="linkmath" href="{% url 'lesson-detail' lessons.pk %}">{{lessons.title}} </a>
                                </h3>
                            {% endfor %}

                        {% endif %} 

                    </div>
                    {% if user.is_authenticated %}
                    {% else %}
                        <div class="card-main">
                            <h2 class="sum_o">Tips!</h2>
                            <p class="sum_p">Login in order to track progress.</p>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

mooc/catalog/templates/catalog/mycourse_list_active_user.html
{% extends "base_generic.html" %}

{% block content %}
  
  <div class="gradient">
    <div class="container">
      <h1 class="course-card-heading"> My Course List</h1>
      <div class="row">
        {% if mycourse_list %}
          {% for myco in mycourse_list %} 
            <div class="col-lg-8 offset-lg-2">                                
              <div class="card-main">
                <div class="course-card-title">
                  <h4 class="ccdt">{{myco.course.title}}</h4>
                        <!-- <p><em> (Last accessed: {{ myco.last_accessed }})</em></p>  --> 
                  <a href="{% url 'lesson' myco.course.pk %}" class="button button--secondary" style="text-decoration: none;">View Course</a></p>
                                    
                  {% if user.is_authenticated %}
                    <a href="{% url 'delete-course-from-list' myco.course.pk %}" class="button button--remove" style="text-decoration: none;">Delete from List!</a>
                  {% endif %}
                </div>
                <p class="course-card-summary">{{myco.course.summary}}</p> 

              </div>
            </div>

          {% endfor %}
        {% else %}
            <p>There are no courses in your list.</p>
        {% endif %}

      </div>
    </div>
  </div>

{% endblock %}

mooc/catalog/templates/catalog/navbar.html
{% load static %}

<nav class="navbar navbar-expand-md navbar-dark bg-dark sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'index' %}"><img src="{% static 'images/logo6.png' %}"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'courses' %}"> All courses</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'teachers' %}"> All teachers</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'my-active' %}">My Courses</a>
          </li>
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Menu
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="{% url 'view-profile' %}"> User: {{ user.get_username }}</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{% url 'logout' %}?next={{request.path}}">Logout</a>
              <a class="dropdown-item" href="{% url 'about-page' %}">About</a>
            </div>
          </div>
        {% else %}
          <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Menu
            </button>
            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
              <a class="dropdown-item" href="{% url 'login' %}?next={{request.path}}">Login</a>
              <a class="dropdown-item" href="{% url 'register' %}?next={{request.path}}">Sign up</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="#">About</a>
            </div>
          </div>
        {% endif %} 
    </div>
  </div>
</nav>

mooc/catalog/templates/catalog/postedby_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Author</h1>

<p>Are you sure you want to delete the author: {{ author }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

mooc/catalog/templates/catalog/postedby_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

mooc/catalog/templates/catalog/postedby_list.html
{% extends "base_generic.html" %}

{% block content %}
  
  <div class="container">
    <h1 class="course-card-heading">Our Teachers</h1>
    <div class="row">
      {% if postedby_list %}
        {% for postedby in postedby_list %}
          <div class="col-lg-8 offset-lg-2">                                
            <div class="card-main">
              <a href="{{ postedby.get_absolute_url }}">{{ postedby.op.first_name }} {{ postedby.op.last_name }}</a>     
            </div>       
          </div>
        {% endfor %}
      {% else %}
        <p>There are no teachers in the site.</p>
      {% endif %}
    </div>  
  </div>

{% endblock %}

mooc/catalog/templates/catalog/profile.html
{% extends 'base_generic.html' %}
{% load pinax_points_tags %}


{% block content %}

<title>Profile</title>
<div class="container">
    <h1 class="course-card-heading"> My Profile Page</h1>
    <div class="row">
        <div class="col-lg-8 offset-lg-2">                                
            <div class="card-main">
                <div class="profinfo">
                    <p><b>Username:</b> {{user}}</p>
                    <p><b>First Name:</b> {{user.first_name}}</p>
                    <p><b>Last Name:</b> {{user.last_name}}</p>
                    <p><b>Email:</b> {{user.email}}</p>
                </div>
                <div class="kentro">
                    <a class="btn btn-primary" href="{% url 'edit-profile' %}">Edit my profile page. </a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <div class="text-center">             
                <div class="card-main">     
                    <h2 class="course-card-heading">How the experience system works</i></h2> 
                    
                        <div class="text-center">
                          <p>For starters you earn experience points by completing lessons, quiz, videos etc. When you reach the 350 mark you will Level Up.</p>
                          <p>When you are level 15 with your experience bar maxed out, you will promoted to the next rank!</p> 
                          <p>Ranking system goes from Bronze -> Silver -> Gold -> Platinum -> Diamond -> Master -> GrandMaster!</p>
                        </div>
                    
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <div class="text-center">              
                <div class="card-main">
                    {% if profile.rank_status == 1 %}
                        <h2 class="course-card-heading">Current Rank: Bronze</h2>
                    {% elif profile.rank_status == 2 %}
                        <h2 class="course-card-heading">Current Rank: Silver</h2>
                    {% elif profile.rank_status == 3 %}
                        <h2 class="course-card-heading">Current Rank: Gold</h2>
                    {% elif profile.rank_status == 4 %}
                        <h2 class="course-card-heading">Current Rank: Platinum</h2>
                    {% elif profile.rank_status == 5 %}
                        <h2 class="course-card-heading">Current Rank: Diamond</h2>
                    {% elif profile.rank_status == 6 %}
                        <h2 class="course-card-heading">Current Rank: Master</h2>
                    {% elif profile.rank_status == 7 %}
                        <h2 class="course-card-heading">Current Rank: GrandMaster</h2>
                    {% endif %}

                    <h3>Level {{ profile.status }} <i class="far fa-star"></i></h3> 
                    <div class="bar-5">
                        <div class="text-center">
                          {{ profile.points }} / 350   
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<style>
.hide {
  display: none;
}

.myDIV:hover + .hide {
  display: block;
  color: #cc9543;
}
</style>

<div class="container">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <div class="text-center">             
                <div class="card-main">      
                    <h2>My Badges</h2> 
                
                        <div class="text-center">
                            
                            {% for badge in userbadges %} 
                                <div class="myDIV"><img src="{{ badge.badg.image.url }}" width="80" height="80"  alt="img"></div>
                                <div class="hide">{{ badge.badg.name }}</div>
                            {% endfor %}

                        </div>

                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

mooc/catalog/templates/catalog/user_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Teacher Information</h1>

  <p><strong> First Name:</strong> {{ user.first_name }}</p>
  <p><strong> Last Name:</strong> {{ user.last_name }}</p>
  <p><strong> E-mail:</strong> {{ user.email }}</p> 

{% endblock %}

mooc/catalog/templates/catalog/user_list.html
{% extends "base_generic.html" %}

{% block content %}
  
  <div class="container">
    <h1 class="course-card-heading">Our Teachers</h1>
    <div class="row">
      {% if teacher_list %}
        {% for teacher in teacher_list %}
          <div class="col-lg-8 offset-lg-2">                                
            <div class="card-main">
              <a href="{{ teacher.get_absolute_url }}">{{ teacher.last_name }} {{ teacher.first_name }}</a>     
            </div>       
          </div>
        {% endfor %}
      {% else %}
        <p>There are no courses in the site.</p>
      {% endif %}
    </div>  
  </div>

{% endblock %}